services:
  paperless-mcp:
    build: .
    ports:
      - "${BRIDGE_PORT}:${BRIDGE_PORT}"
    environment:
      NODE_ENV: development
      BRIDGE_PORT: ${BRIDGE_PORT}
    volumes:
      - ./.env:/app/.env